### ISSUE TITLE
fatal error: lzma.h: No such file or directory

### ISSUE THREAD

**Issue by richp10** [danielrh/go-xz#2]
Compilation terminated

**Comment by danielrh** [comment]
`sudo apt-get install liblzma-dev` maybe?

**Comment by neoshui** [comment]
> `sudo apt-get install liblzma-dev` maybe?

I meet this error for win10 ， I can’t fix that

**Comment by danielrh** [comment]
This library isn't standalone and requires the C liblzma to run. You can install it by unzipping the .lib and .h from the "Prebuilt binaries" section here https://tukaani.org/xz/

if you want decompression only and want to avoid a C lib you can use the golang native version
https://github.com/xi2/xz

if you need both and want to avoid a C lib you can look at the (experimental) https://github.com/ulikunitz/xz
